### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by acolley** [sebcrozet/ncollide#100]
Are there any plans to give `ncollide` (and by association `nalgebra` and `nphysics`) support for concurrency (i.e. implement Send etc.)? I'm trying to share a `DBVT` and a custom structure with embedded `nalgebra` structures (e.g. `Vec3`, `Pnt3`...) across threads in order to parallelise my ray tracer but since `Send` is not implemented for these structures I can't wrap them in an `Arc`.

Is there a recommended way to do this or is it just not possible currently?

Thanks.

**Comment by acolley** [comment]
Ok so after reading the compilation error messages more closely it seems it's the usage of `RefCell` inside the `DBVT` that's preventing it from being used as `Send` and `Sync`.

I've solved my immediate issue by using the `BVT` instead which does not use `RefCell` and so does not suffer from this particular problem.

I guess it would be quite hard to have the functionality of the `DBVT` in a concurrent environment.

**Comment by sebcrozet** [comment]
Yes, because DBVT is dynamically modifiable, it is hardly usable concurrently. I believe that an efficient concurrency-enabled dynamically modifiable space partitioning structure would be very different from the current DBVT implementation anyway.

I have the feeling that you found an acceptable alternative for this issue, so I am closing this. Feel free to reopen if I misunderstood your request.
