### ISSUE TITLE
Trait implementations for Ball<f32> required?

### ISSUE THREAD

**Issue by viperscape** [sebcrozet/ncollide#108]
I'm not sure how to handle this issue, I want to store BoundingSphere in a map, but I get errors. Any help is appreciated, thanks!

Errors: 
```44:2 error: the trait `ncollide_math::Point` is not implemented for the type `ncollide_entities::shape::ball::Ball<f32>` [E0277]```

```error: the trait `core::ops::Index<usize>` is not implemented for the type `ncollide_entities::shape::ball::Ball<f32>` [E0277]```

```error: the trait `core::ops::Neg` is not implemented for the type `ncollide_entities::shape::ball::Ball<f32>` [E0277]```

```error: the trait `core::ops::Sub` is not implemented for the type `ncollide_entities::shape::ball::Ball<f32>` [E0277]```

While this dos not work: 

``` rust
pub struct Things {
    m: HashMap<u32,BoundingSphere<Ball<f32>>>,
}
```

This does:

```rust
pub struct Things {
    m: HashMap<u32,Ball<f32>>,
}
```

**Comment by viperscape** [comment]
It would be ideal if BoundingSphere only stored f32 as its type and not Pnt3 or Ball in this case. Is this possible?

**Comment by sebcrozet** [comment]
Sorry for the delay, I forgot about this issue.

A `BoundingSphere` cannot store only a `f32` as it has to know the type of its center (which is a point). Also you are getting all those errors because `BoundingSphere<Ball<f32>>` is invalid : its type parameter is the bounding sphere center's type, not the geometric shape it bounds.

So you have to use: `HashMap<u32, BoundingSphere<Pnt3<f32>>>` here.

**Comment by viperscape** [comment]
Ah ok, this makes sense. Thanks for the reply!
