### ISSUE TITLE
Ball vs Triangle TOI enters infinite loop

### ISSUE THREAD

**Issue by Connicpu** [sebcrozet/ncollide#123]
I have encountered an issue where sometimes time_of_impact with ball vs triangle just never returns (I assume it enters an infinite loop). I was able to capture the exact input which was passed to time_of_impact to make it bug out.

EDIT: Never mind, this output isn't reproducable, so I'm not quite sure why it's freezing, but it does it on debug and release builds alike.

**Comment by sebcrozet** [comment]
Sorry, I fail to reproduce the bug. Here is the code I executed. Please correct me if I misread your input. Here, it is assumed that you used 32-bit floats (the bug is not reproduced with 64-bit either):

```rust
extern crate nalgebra as na;
extern crate ncollide;

use na::{Iso2, Vec2, Pnt2};
use ncollide::shape::{Ball, Triangle};
use ncollide::geometry;

fn main() {
    let b = Ball::new(0.375f32);
    let t = Triangle::new(Pnt2::new(0.5, -0.5), Pnt2::new(-0.5, -0.5), Pnt2::new(-0.5, 0.5));


    let m1 = Iso2::new(Vec2::new(11.590705, 5.927473), na::zero());
    let m2 = Iso2::new(Vec2::new(11.5, 5.5), na::zero());

    let cast = geometry::time_of_impact(&m1, &Vec2::new(0.0, -0.016684677), &b, &m2, &na::zero(), &t);

    println!("cast: {}", cast.unwrap());
}
```

Because this is probably related to floating-point rounding errors, could you, if at all possible:
  * Re-run your program using a different precision than the current one (e.g. f64 if you are currently using f32) and attempt to reproduce the bug.
  * Provide more precise numbers (or, even better, their hexadecimal machine representations). I believe that more than only six digits will be necessary to actually reproduce the bug.

This looks like a convergence issue for the `implicit_toi_and_normal_with_ray` from `ncollide_queries/ray/ray_support_map.rs` or the underlying gjk executions because it seems that the two objects are nearly-touching.

**Comment by Connorcpu** [comment]
Sorry, I had narrowed it down to the wrong call to time_of_impact. I was able to figure out that it happened when v1.x was *incredibly* small, specifically this velocity:
```
Vec2 {
    x: -0.000000000000000000000000000000000000000006925,
    y: 0
}

**Comment by sebcrozet** [comment]
Well, to be honest, I have no idea how my implementation behaves with that kind of input! The following seems to produce an infinite loop:

```rust
extern crate nalgebra as na;
extern crate ncollide;

use na::{Iso2, Vec2, Pnt2};
use ncollide::shape::{Ball, Triangle};
use ncollide::geometry;

fn main() {
    let b = Ball::new(0.375f32);
    let t = Triangle::new(Pnt2::new(0.5, -0.5), Pnt2::new(-0.5, -0.5), Pnt2::new(-0.5, 0.5));


    let m1 = Iso2::new(Vec2::new(0.0, 0.0), na::zero());
    let m2 = Iso2::new(Vec2::new(11.5, 5.5), na::zero());
    let dir = Vec2::new(0.0, 0.000000000000000000000000000000000000000006925);

    let cast = geometry::time_of_impact(&m1, &dir, &b, &m2, &na::zero(), &t);

    println!("cast: {:?}", cast);
}
```

As expected, it runs fine with 64-bit floats.
I will investigate this further but it might take some time to write something completely robust.

**Comment by Connorcpu** [comment]
That's fine, for my purposes I was able to fix it with a simple `if velocity.x < epsilon` check :)

**Comment by Connicpu** [comment]
Hey, thanks! 😄
