### ISSUE TITLE
Getting additional information from a point query

### ISSUE THREAD

**Issue by hannobraun** [sebcrozet/ncollide#147]
I'm using ncollide to project a point onto a `Polyline`. In addition to the projected point, I'd like to get more projection information that is specific to `Polyline`, namely the index of the segment the point was projected on, and where on that segment it was projected.

All of that information is available in the code that computes the point query for `Polyline`[1][2], so I figured it shouldn't be too difficult to extract that additional information using the following approach:
1. Add a generic field for shape-specific info to `PointProjection`
2. Add a matching associated type to `PointQuery`
3. Modify the `Polyline`/`BaseMesh` return the additional info I need

Here's what I have so far: https://github.com/hannobraun/ncollide/compare/master...point-query

The next step would be to set the `ProjectionInfo` for `Polyline` to `PointProjectionInfo` instead of `()`, but I'm running into a wall there. Doing so conflicts with the [implementation of `Shape::as_point_query`](https://github.com/hannobraun/ncollide/blob/point-query/ncollide_geometry/shape/shape_impl.rs#L53). Heres what I've tried, and why it won't work:
1. Return `PointQuery<P, M, ProjectionInfo=<Self as PointQuery>::ProjectionInfo>`: `Shape` isn't allowed to refer to `Self`, or it can't be used as a trait object any more.
2. Return `PointQuery<P, M, ProjectionInfo=()>`: That of course only works for types that have `ProjectionInfo` set to `()`. Allowing `PointQuery` implementations to set it to other types is the whole point.
3. Return some kind of proxy instead of `self`: I tried adding a type that contains a reference to a `PointQuery` and implements `PointQuery` with `ProjectionInfo=()` itself. Its `project_point` implementation just calls the `project_point` of the other `PointQuery` and strips the type-specific information from the result. That can't work either, as `as_point_query` returns a reference, and I can't return a reference to a proxy type I just constructed on the stack.

The next logical step for me is to dive deeper into the code to find out how `as_point_query` is used, and maybe find a way to change it, so it doesn't stand in the way of the feature I'm trying to build here. However, I figured before I do that, I'd stop by here to ask these questions:
1. Is there maybe a simpler solution I'm missing?
2. If I can work this out, has this feature a chace of being merged?

[1] Segment index available here: https://github.com/sebcrozet/ncollide/blob/5f40c3956e42de134d8c8ab737cbc2683d1632a0/ncollide_geometry/query/point_internal/point_mesh.rs#L57
[2] Projection location on the segment available here: https://github.com/sebcrozet/ncollide/blob/5f40c3956e42de134d8c8ab737cbc2683d1632a0/ncollide_geometry/query/point_internal/point_segment.rs#L30

**Comment by sebcrozet** [comment]
That would be a very useful feature, and would gladly be merged! Actually, finding a solution for point-projection is interesting because we could then do something similar for, e.g., ray-casting.

I think your approach is the right one here and I understand how `Shape` can be an issue. On additional solution would be not to make the projection info generic: we could just assume that all we will ever need is an integer, so we could add a `usize` field to `PointProjection` that would be filled only by triangle meshes, compound shapes, and polylines. I don't really like this option, but this would prevent `Shape` from causing problems. Another more generic option is to add a `Box<Any>` field but that's clearly not efficient. Perhaps we could get some ideas by looking into other engines like Bullet or Box2D? I'm pretty sure they had to face a similar issue at some point!

I can explain what the `Shape` trait does to help figuring out what could be a solution. The first obvious goal of the `Shape` trait is to let the user be generic wrt. the geometrical shape of its object. The problem, though, is that different shapes can have:

* Different mathematical description: support mapping or compound shape.
* Different features: ray-casting and point-projection.

All the `.as_` methods of the shape trait (like `.as_point_query`) are here to allow a downcast from the `Shape` trait to the feature-specific trait, e.g., `PointQuery`. This is necessary because Rust does not have anything like the C++ `dynamic_cast` between traits (because of the way the vtable is handled by the compiler). One way to overcome this limitation would be to define Shape as: `trait Shape : PointQuery + RayCast` but I did not want to because I don't want to force a user of `Shape` to implement those feature traits for its custom geometry if ray-casting or point queries are not needed by its applications. Anyway, even if we wrote `trait Shape: PointQuery + RayCast` we would have to choose a concrete type for the `ProjectionInfo`.

So right now, I can't think of a very satisfying solution unfortunately.

**Comment by hannobraun** [comment]
Thanks a lot for your reply. Great to know that I'm at least on the right track as far as desirability of the feature is concerned.

I'll keep looking into it, but as I need this for a low-pressure hobby project, it may take a while. In case we can't find a good solution, maybe `Box<Any>` isn't a bad suggestion, actually. In principle, I'd rather have access to information inefficiently, than having no access at all. What I don't like about it, is that the `Box` causes overhead for everyone, whether you need that additional info or not.

**Comment by hannobraun** [comment]
I got it :-D
Pull request: #148
