### ISSUE TITLE
Triangular shape with Shape+Clone?

### ISSUE THREAD

**Issue by floere** [sebcrozet/ncollide#202]
Hi dear ncollide maintainers 👋 

I'd like to use a 2d triangular shape for collisions – which implements both `Shape` and `Clone`.
First, I tried to use `shape::Triangle`, but even though it's available in ncollide2d, it appears to use the feature switch `dim3`, http://www.ncollide.org/rustdoc/src/ncollide2d/shape/shape_impl.rs.html#79-84.
Then, I looked at `shape::ConvexPolygon`, which appears to be the way to go for a triangular 2d shape. However, `ConvexPolygon` does not implement `Clone`.
Is there a specific reason for this? And am I looking at the wrong shapes?

I am using ncollide2d 0.15.3 – really am impressed by this library so far, great work! 😊

**Comment by sebcrozet** [comment]
Hi! `ConvexPolygon` is indeed the right shape to use here. `Triangle` does not implement `Shape` in 2D. `ConvexPolygon` should implement `Clone` but it seems I forgot to make it so.

**Comment by floere** [comment]
@sebcrozet Thanks for the quick answer, Sébastien, much appreciated! I'm relieved to hear it's just an oversight 😊I'm closing this – if it's against Repo policy, please reopen. Thanks again 😊

**Comment by sebcrozet** [comment]
@floere Actually, there is usually no need to close an issue manually (unless if it is not going to be fixed). It will automatically be closed by github as soon as the corresponding pull request #203 is merged. That way, you will get a notification from github as soon as the fix is merged to master (and I usually publish it to crates.io soon after that).

**Comment by floere** [comment]
@sebcrozet Ah I see, thanks – I'll not close it in the future 😊
